version: "3.9"

networks:
  satoshi-dev-link:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24

services:
  django-dev: &django
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: satoshi_django_image:latest
    container_name: satoshi_django_dev_container
    volumes:
      - ./app:/app
    restart: always
    depends_on:
      - redis-dev
    networks:
      - satoshi-dev-link
    env_file:
      - ./.env
    ports:
      - "10106:10106"

  redis-dev:
    image: redis:7.2.1-alpine3.18
    container_name: satoshi_redis_dev_container
    restart: always
    networks:
      - satoshi-dev-link

  celeryworker-dev:
    <<: *django
    image: satoshi_celeryworker_image:latest
    container_name: satoshi_celery_dev_container
    env_file:
      - ./.env
    restart: always
    ports: []
    command: /start-celeryworker
    networks:
      - satoshi-dev-link
    depends_on:
      - redis-dev

  celerybeat-dev:
    <<: *django
    image: satoshi_celerybeat_image:latest
    container_name: satoshi_celerybeat_dev_container
    env_file:
      - ./.env
    restart: always
    ports: []
    command: /start-celerybeat
    networks:
      - satoshi-dev-link
    depends_on:
      - redis-dev