# Generated by Django 5.0.1 on 2024-04-05 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscribe", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usersubscription",
            unique_together={("message_type", "user")},
        ),
    ]
